### ISSUE TITLE
Maybe access to the Toggle Console?

### ISSUE THREAD

**Issue by PotatoesSuck** [supexian/swagpex#2]
Description:
Maybe, there is a way to get access to the Toggle Console (the thing that VIP servers owners allows to change resources and such).

Implementation:
It would allow to pretty much have access to country units, change things to yourself, etc. Ig.

Additional Context:
Also, can you give me access to the talk role? I asked this a bit ago but never responded. My discord user is blackhawk05884

**Comment by supexian** [comment]
Has been Tested. Does not work...
unless i am too stupid for it :^(
